# Java Dockerfile - Auto-generated by BlackRoad Deploy
# Supports: Spring Boot, Maven, Gradle

# Build stage
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copy build files
COPY pom.xml* build.gradle* settings.gradle* ./
COPY src ./src

# Build application
RUN if [ -f "pom.xml" ]; then mvn clean package -DskipTests; \
    elif [ -f "build.gradle" ]; then gradle build -x test; fi

# Runtime stage
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Copy JAR from build stage
COPY --from=build /app/target/*.jar app.jar 2>/dev/null || \
     COPY --from=build /app/build/libs/*.jar app.jar

# Expose port (default 8080)
EXPOSE ${PORT:-8080}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=60s \
  CMD wget -q -O- http://localhost:${PORT:-8080}/actuator/health || exit 1

# Start application
CMD ["java", "-jar", "app.jar"]
