# Go Dockerfile - Auto-generated by BlackRoad Deploy
# Supports: Go modules

# Build stage
FROM golang:1.22-alpine AS build

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum* ./
RUN go mod download

# Copy source code
COPY . .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy binary from build stage
COPY --from=build /app/main .

# Expose port (default 8080)
EXPOSE ${PORT:-8080}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s \
  CMD wget -q -O- http://localhost:${PORT:-8080}/health || exit 1

# Start application
CMD ["./main"]
